### ISSUE TITLE
do not replace header, start timer after stop

### ISSUE THREAD

**Issue by DanielRuf** [ToX82/server-timing-helper#1]
Since there is no direct `start`/ `stop`, it makes sense to use it as some sort of automatic stopwatch and each line stops the last metric and starts a new one.

But a `start`/ `stop`for direct usage makes much more sense in general.

Also it seems the header was replaced (because `$replace` is `true` by default, see https://www.php.net/manual/de/function.header.php) and so multiple metrics did not work (only the last one was loaded).

```diff
--- ServerTiming.php	2024-07-22 23:35:29.000000000 +0200
+++ ServerTiming.php	2024-07-22 23:33:04.000000000 +0200
@@ -69,10 +69,9 @@
     {
         if (isset(self::$timers[$metricName])) {
             $durationInMicroseconds = self::stop($metricName);
-            header("Server-Timing: " . $metricName . ";dur=" . $durationInMicroseconds . ";desc=" . $metricName);
-        } else {
-            self::start($metricName);
+            header("Server-Timing: " . $metricName . ";dur=" . $durationInMicroseconds . ";desc=" . $metricName, false);
         }
+        self::start($metricName);
     }
 
     /**
@@ -88,9 +87,8 @@
             $totalCalls = self::$totals['calls'][$metricName];
             $totalInMicroseconds = self::$totals['time'][$metricName];
             error_log('Server-Timing: ' . $metricName . " stop - (" . round($durationInMicroseconds, 5) . " ms - called " . $totalCalls . " times, total time: " . round($totalInMicroseconds, 5) . " ms)");
-        } else {
-            self::start($metricName);
-            error_log('Server-Timing: ' . $metricName . " start");
         }
+        self::start($metricName);
+        error_log('Server-Timing: ' . $metricName . " start");
     }
 }
```

**Comment by ToX82** [comment]
Hello @DanielRuf , thanks for pointing that out, I didn't notice about the `$replace` issue.

I am currently working on a pretty big rewrite of this tool, it'll be out as soon as possible and will solve that issue.
The `start` and `stop` methods will be available as well.

**Comment by ToX82** [comment]
V. 1.3.0 has been published. Please check the updated README file
